### ISSUE TITLE
Add example of serving /web_service

### ISSUE THREAD

**Issue by jbrowngithubuser** [cmrunton/tls-dashboard#11]
To help people get started quickly with the project, under [Web Service Setup](https://github.com/cmrunton/tls-dashboard#web-service-setup) can you add the example of serving the page e.g.

```
cd tls-dashboard/web_service
python -m SimpleHTTPServer 8080
```

...but mention that it's better to serve it over TLS, given it's a site to do with TLS :)

**Comment by cmrunton** [comment]
@jbrowngithubuser I can add a bit more description to the Web Service Setup section, but you don't need to establish a local web server to view the Dashboard. Everything is contained in the `web_service` directory and all the links are relative, so all you have to do is open `index.html` in your browser of choice.
