### ISSUE TITLE
Support SNI and invalid certs

### ISSUE THREAD

**Issue by jbrowngithubuser** [cmrunton/tls-dashboard#7]
If a cert is invalid (e.g. it has already expired) or the host uses SNI the node script can fail.

To fix this add

```
rejectUnauthorized: False
servername: hostname_goes_here
```

to `var options =`

**Comment by cmrunton** [comment]
@jbrowngithubuser Can you give me a hostname that uses SNI that fails? I use SNI on all of my dev servers, and the script works just fine.
