### ISSUE TITLE
Support non-default ports and paths

### ISSUE THREAD

**Issue by jbrowngithubuser** [cmrunton/tls-dashboard#8]
Support specifying ports and paths (but don't require them) in monitored_hosts.js e.g.

```
var hosts = [
  'www.example.com',
  'www.example.com:8080',
  'www.example.com/foo/bar.html',
  'www.example.com:3443/foo/bar.html',
];
```

**Comment by cmrunton** [comment]
@jbrowngithubuser I can see the usefulness of checking non-standard ports, but I'm not following the need to check different paths. Could you explain the use case here for me?

**Comment by apple314159** [comment]
See pull request. It handles non-default ports.

**Comment by cmrunton** [comment]
Added non-standard ports in v2.0.0. Don't see a use case for alternative paths.
